### ISSUE TITLE
[Feature request] Add long break

### ISSUE THREAD

**Issue by plakhin** [Neway6655/Sublime-Pomodoro#11]
It would be nice to have ability to add long breaks for configurable number of minutes after configurable number of working sessions. 

Example: 30 minutes break after 4 sessions:
```
25 minutes - 1st work session
 5 minutes - 1st break
25 minutes - 2nd work session
 5 minutes - 2nd work session
25 minutes - 3rd work session
 5 minutes - 3rd work session
25 minutes - 4th work session
30 minutes - LONG BREAK
```

**Comment by Neway6655** [comment]
Hi plakhin,

Thanks for your comments, I have committed a version(https://github.com/Neway6655/Sublime-Pomodoro/commit/f1c46d958b359485b6e99ec56c62c4c315b3642a) for this "long break" feature.

You can update pomodoro package to get the new version and check if it works as you expected.

**Comment by donbalon4** [comment]
@Neway6655 I think you can close this issue.
