### ISSUE TITLE
feature_request(enhancement): pause

### ISSUE THREAD

**Issue by Kristinita** [Neway6655/Sublime-Pomodoro#16]
### 1. Summary

It would be nice, if would be possible to make a pauses inside a Pomodoro working minutes.

### 2. Argumentation

Ideally, I should only pause at the end of the working minutes. But in real world it is problematically. I get distracted at work, examples are:

+ the phone rings,
+ distract colleagues,
+ summons the bosses,

and so on. It takes me time; I can't use all the working minutes at work. It would be nice, if user can use all working minutes for working.

### 3. Example of expected behavior

I run Pomodoro → for example, my `Working time remaining` is 14 minutes → boss distract me at work → `Pomodoro: Pause` → I'm ready to work again → `Pomodoro: Resume` → my `Working time remaining` is still 14 minutes; that is, I had to work as long as it was before the pause.

Thanks.

**Comment by Neway6655** [comment]
emm... I think if I am interrupted once my pomodoro started, then I prefer to start another new pomodoro than resume it when I come back to my work.

**Comment by donbalon4** [comment]
Unfortunately, I have experienced the same situations that @Kristinita describe. I think that i would be nice to have a feat like that. Many times the interruptions don't justificate to start a new pomodoro (e.g. 3-5 mins), and this enhancement makes this tool more flexible. If you @Neway6655 want, I could work on it ;).

**Comment by Neway6655** [comment]
OK, if you guys think this feature is helpful to your daily work, then I think it is worthy to be added. 

@donbalon4 sure, I am very appreciated that you can work on it, thanks!

**Comment by Kristinita** [comment]
**Status: :heavy_check_mark: Added** by @donbalon4.

It works for me. Thanks!
