### ISSUE TITLE
[Bug] Not can begin to use Pomodoro

### ISSUE THREAD

**Issue by Kristinita** [Neway6655/Sublime-Pomodoro#6]
### Summary

I can not begin to use Pomodoro.
### Expected behavior

Successfully begin to work.
### Actual behavior

``` python
command: pomodoro
Traceback (most recent call last):
  File "E:\Sublime Text Build 3126 For Debug\sublime_plugin.py", line 818, in run_
    return self.run(edit)
TypeError: run() missing 2 required positional arguments: 'workingMins' and 'restingMins'
```
### Steps to reproduce

I tested on a version of Sublime Text without plugins and user settings.

I install Pomodoro → restart Sublime Text → <kbd>Ctrl+Shift+P</kbd> → `pomodoro` → I get stack trace. 
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by Neway6655** [comment]
Hi Kristinita,

My Sublime Text's version is also build 3126, but I can not reproduce your problem on my Mac.

I need to find an windows system...

BTW, have you did the following settings, as mentioned in the README:

Add the line below to your "Preferences: Key Bindings - User" settings:
{ "keys": ["ctrl+shift+p"], "command": "pomodoro", "args": {"workingMins": 25, "restingMins": 5} }

**Comment by Kristinita** [comment]
@Neway6655 , please, add for Pomodoro [`sublime-settings`](https://www.sublimetext.com/docs/3/settings.html) file with parameters `workingMins` and `restingMins` like in all other plugins, when users can change settings not only in keymap.

Thanks.

**Comment by Neway6655** [comment]
close it, the sublime-settings files are already provided.
