### ISSUE TITLE
[Bug] NameError: global name 'stop' is not defined

### ISSUE THREAD

**Issue by Kristinita** [Neway6655/Sublime-Pomodoro#9]
### Summary

I want interrupt Pomodoro and run Pomodoro again in each time. But if I close Pomodoro popup after rest time, I can not run Pomodoro without Sublime Text restart.

### Expected behavior

Successful new run Pomodoro after closing each time.

### Actual behavior

```python
Exception in thread Thread-36:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "pomodoro in E:\Sublime Text 3\Data\Installed Packages\Pomodoro.sublime-package", line 83, in run
NameError: global name 'stop' is not defined
```

### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

If rest time was ended for me, I saw popup window:

> Come on, let's continue

I close window (<kbd>Alt+F4</kbd> in Windows) → <kbd>Ctrl+Shift+P</kbd> → `Pomodoro: Run Pomodoro` → I get stack trace, Pomodoro not run for me.

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by Neway6655** [comment]
Thanks for you issue...

But sorry that I don't have much time to fix these issues(including previous ones.), because I am busy working on the famous 11.11 (the Chinese's e-commerce festival On Nov. 11th) for over a month....

Or you can try to commit a PR if you have found the root cause.

Thanks!

**Comment by Kristinita** [comment]
It is not critical bug, we can waiting. Thanks for plugin!

**Comment by Neway6655** [comment]
Fixed. 

Please have a check with the latest build tonight.

https://github.com/Neway6655/Sublime-Pomodoro/commit/302c37293f7216c87fa8b8b4a2c56f1ab05271a3

**Comment by Kristinita** [comment]
@Neway6655 , thanks, now I can not get stack trace!
